import './globals.scss'
import type { Metadata } from 'next'
import { Inter, JetBrains_Mono } from 'next/font/google'

const jetBrainsMono = JetBrains_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className='dark' >
			<body className={jetBrainsMono.className}>{children}</body>
		</html>
	)
}
